name: 4c16
channels:
    - conda-forge
dependencies:
    - flask-socketio
    - eventlet
    - pip:
        - Pillow
        - numpy
        - h5py
        - tensorflow
        - keras
        - lycon
